# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e7e0d4cbb7a9bb4e62ea22315e50c573e7d57ecea30be29a38378f3f9a24a287ed22001714b0cf241dba95aa45022676b2ca2ac768fb1db71bbb51d22891038

test:
  secret_key_base: e0438070a6f8fcacc704e04bec5a85aed488d961469ce513fe09caf672e6aa2d4c43451a5a1fa2a623fe6d8f9dc6938e89c2e2ef40301309fb07be523a2e3fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
